apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}
---
apiVersion: v1
kind: Namespace
metadata:
  name: limit-example-${namespace}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workshop-user
  namespace: ${namespace}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workshop-user-limit
  namespace: limit-example-${namespace}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: workshop-user
  namespace: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workshop-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ${user}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: workshop-user-limit
  namespace: limit-example-${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workshop-user-limit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ${user}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: workshop-user-binding-${namespace}
  namespace: ${namespace}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: ${user}
